scoreboard objectives add muteki dummy
scoreboard objectives add doraammo dummy
scoreboard objectives add dora_ct dummy
scoreboard objectives add doracharge dummy
scoreboard objectives add dorareload dummy
scoreboard objectives add indoraammo dummy
scoreboard objectives add doragun_life dummy
scoreboard objectives add praammo dummy
scoreboard objectives add pra_ct dummy
scoreboard objectives add pracharge dummy
scoreboard objectives add prareload dummy
scoreboard objectives add inpraammo dummy
scoreboard objectives add pragun_life dummy
scoreboard objectives add math1 dummy
scoreboard objectives add bleeding dummy
scoreboard objectives add bloodtier dummy
scoreboard objectives add bloodsecond dummy
scoreboard objectives add bloodtime dummy
scoreboard objectives add bloodtierkari dummy
scoreboard objectives add eshock dummy
scoreboard objectives add ieshock dummy
scoreboard objectives add thunder_crash_recharge dummy
scoreboard objectives add thunder_time dummy
scoreboard objectives add elect dummy
scoreboard objectives add select_ct dummy
scoreboard objectives add thunder_p_ct dummy
scoreboard objectives add last_bolt dummy
scoreboard objectives add frash dummy